var Mathematics=75.25;
console.log(Mathematics);
var Biology=65;
console.log(Biology);
var Chemistry=80;
console.log(Chemistry);
var Physics=35.45;
console.log(Physics);
var Bangla=99.50;
console.log(Bangla);
var result=(Mathematics+Biology+Chemistry+Physics+Bangla)/5;
result=result.toFixed(2);
console.log(result);